version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/.github/workflows"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 99
    groups:
      workflows-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    versioning-strategy: lockfile-only
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 99
    groups:
      poetry-dependencies:
        patterns:
          - "*"
