[tool.poetry]
name = "ssb-datadoc"
version = "0.1.1"
description = "Document dataset metadata. For use in Statistics Norway's metadata system."
authors = ["Statistics Norway <mmw@ssb.no>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/statisticsnorway/datadoc"

packages = [
    { include = "datadoc" },
]
include = ["datadoc/*", "klargjorte_data/*"]

[tool.poetry.scripts]
datadoc = 'datadoc:main'

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.27.1"
pyarrow = "^8.0.0"
jupyter-dash = "^0.4.2"
dash = "^2.4.1"
pydantic = "^1.9.1"
dash-bootstrap-components = "^1.1.0"
pandas = "^1.4.2"
ssb-datadoc-model = "0.1.0"

[tool.poetry.dev-dependencies]
jupyter = "^1.0.0"
ipykernel = "^6.13.0"
notebook = "^6.4.12"
flake8 = "^4.0.1"
mypy = "^0.950"
black = "^22.3.0"
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
nbstripout = "^0.5.0"
bump2version = "^1.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
