[tool.poetry]
name = "datadoc"
version = "0.1.0"
description = "A tool for documentation of datasets from within a Jupyter environment"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
ipywidgets = "^7.7.0"
ipysheet = "^0.5.0"
requests = "^2.27.1"
pyarrow = "^8.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
