[tool.poetry]
name = "ssb-datadoc"
version = "0.1.4"
description = "Document dataset metadata. For use in Statistics Norway's metadata system."
authors = ["Statistics Norway <mmw@ssb.no>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/statisticsnorway/datadoc"

classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: Dash",
    "Typing :: Typed"
]

packages = [
    { include = "datadoc" },
]

[tool.poetry.scripts]
datadoc = 'datadoc.app:main'

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.27.1"
pyarrow = "^8.0.0"
jupyter-dash = "^0.4.2"
dash = "^2.4.1"
pydantic = "^1.9.1"
dash-bootstrap-components = "^1.1.0"
pandas = "^1.4.2"
ssb-datadoc-model = "0.1.3"
dapla-toolbelt = "^1.3.1"
gcsfs = "^2022.7.1"

[tool.poetry.group.dev.dependencies]
jupyterlab = "^3.4.5"
ipykernel = "^6.13.0"
mypy = "^0.950"
black = "^22.3.0"
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
nbstripout = "^0.5.0"
bump2version = "^1.0.1"
flake8 = "*"
flake8-bugbear = "*"
flake8-builtins = "*"
flake8-comprehensions = "*"
flake8-debugger = "*"
flake8-eradicate = "*"
flake8-logging-format = "*"
isort = "*"
python-kacl = "*"
pyupgrade = "*"
tryceratops = "*"
pep8-naming = "*"
pre-commit = "^2.20.0"
autoflake = "^1.4"
pytest-mock = "^3.8.2"
ipython = "^8.4.0"
poethepoet = "^0.16.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poe.tasks]
test = "pytest -vvvv --cache-clear --cov-report=term-missing --cov=."
bump-patch-version = "bump2version patch"
jupyter = "jupyter lab"
datadoc = "python datadoc/app.py"

[tool.isort]
profile = "black"
src_paths = ["datadoc"]

[tool.black]
target-version = ["py37", "py38", "py39"]
include = '\.pyi?$'
